import fs from 'node:fs';
import process from 'node:process';
import {
	endGroup,
	info,
	setOutput,
	startGroup,
	warning,
	error as logError,
	setFailed,
} from '@actions/core';
import {Octokit} from '@octokit/action';
import {formatTitle} from './format-title.js';
import {getInputs, processInputs} from './inputs.js';

const event = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH));

const octokit = new Octokit();

/**
 * Retry a function with exponential backoff
 * @param {Function} function_ - The async function to retry
 * @param {number} maxRetries - Maximum number of retries
 * @param {number} initialDelay - Initial delay in milliseconds
 */
async function withRetry(function_, maxRetries = 3, initialDelay = 1000) {
	let lastError;

	for (let attempt = 0; attempt <= maxRetries; attempt++) {
		try {
			// eslint-disable-next-line no-await-in-loop
			return await function_();
		} catch (error) {
			lastError = error;

			// Don't retry on client errors (4xx), only on server errors (5xx) or network issues
			if (error.status && error.status >= 400 && error.status < 500) {
				throw error;
			}

			if (attempt < maxRetries) {
				const delay = initialDelay * (2 ** attempt);
				warning(`Attempt ${attempt + 1} failed: ${error.message}. Retrying in ${delay}ms...`);
				// eslint-disable-next-line no-await-in-loop
				await new Promise(resolve => {
					setTimeout(resolve, delay);
				});
			}
		}
	}

	throw lastError;
}

async function getCurrentTitle({owner, repo, number}) {
	// Read the title from via API to support multiple actions in a row making changes to the title
	return withRetry(async () => {
		const {data} = await octokit.rest.issues.get({
			owner, repo, issue_number: number,
		});

		return data.title;
	});
}

function readEnv() {
	if (!['issues', 'pull_request', 'pull_request_target'].includes(process.env.GITHUB_EVENT_NAME)) {
		throw new Error('Only `issues`, `pull_request`, and `pull_request_target` events are supported. Received: ' + process.env.GITHUB_EVENT_NAME);
	}

	if (!['opened', 'edited'].includes(event.action)) {
		throw new Error(`Only types \`opened\` and \`edited\` events are supported. Received: ${process.env.GITHUB_EVENT_NAME}.${event.action}`);
	}

	const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
	const {number} = event.issue ?? event.pull_request;

	return {
		owner,
		repo,
		number,
	};
}

async function run() {
	try {
		const {owner, repo, number} = readEnv();
		const title = await getCurrentTitle({owner, repo, number});

		// Validate title
		if (!title || typeof title !== 'string') {
			throw new Error('Invalid title received from GitHub API');
		}

		if (title.length > 256) {
			warning(`Title is very long (${title.length} characters). This may cause issues.`);
		}

		startGroup('Environment');
		info(JSON.stringify({
			owner, repo, number, title,
		}, null, 2));
		endGroup();

		const inputs = getInputs();
		const processedInputs = processInputs(inputs);
		startGroup('Inputs');
		info(JSON.stringify({inputs, processedInputs}, null, 2));
		endGroup();

		const newTitle = formatTitle(title, processedInputs);

		// Validate new title
		if (!newTitle || typeof newTitle !== 'string') {
			throw new Error('Invalid title generated by formatTitle');
		}

		if (newTitle.length > 256) {
			throw new Error(`New title is too long (${newTitle.length} characters). GitHub limits titles to 256 characters.`);
		}

		const changeNeeded = title !== newTitle;
		setOutput('title', newTitle);
		setOutput('changed', changeNeeded);

		info(`Title: "${newTitle}"`);

		if (title === newTitle) {
			info('No title changes needed');
			return;
		}

		info(`New title: "${newTitle}"`);

		if (inputs.dryRun) {
			info('Dry run: No changes applied');
			return;
		}

		// Update the title with retry logic
		await withRetry(async () => {
			await octokit.issues.update({
				owner, repo, issue_number: number, title: newTitle,
			});
		});

		// Verify the update succeeded
		const updatedTitle = await getCurrentTitle({owner, repo, number});
		if (updatedTitle === newTitle) {
			info('Title updated successfully');
		} else {
			warning(`Title update may not have succeeded. Expected: "${newTitle}", Got: "${updatedTitle}"`);
		}
	} catch (error) {
		logError(`Action failed: ${error.message}`);
		if (error.stack) {
			logError(error.stack);
		}

		setFailed(error.message);
		throw error;
	}
}

// eslint-disable-next-line unicorn/prefer-top-level-await
run();
