name: Self
on:
  pull_request_target:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Self:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        name: Local action
        with:
          keywords: passiflora, cumulonimbus, amorphophallus
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        name: Local action repeated check (should not override)
        with:
          keywords: kunyit
          prefix: asem
          token: ${{ secrets.GITHUB_TOKEN }}
